theme: jekyll-theme-minimal

title: Cooking, Programming, Parenting
description: Not necessarily in that order.

permalink: /:categories/:year/:month/:title:output_ext

twitter_username: maneeshasane
github_username:  maneesha
linkedin_username: maneeshasane